services:
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: g31-user-service:latest
    env_file:
      - ./user-service/.env
    # environment:
    #   - NODE_ENV=production
    #   - USER_SERVICE_PORT=4001
    #   - DATABASE_URL=${DATABASE_URL}
    #   - JWT_SECRET=${JWT_SECRET}
    #   - REDIS_URL=${REDIS_URL}
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - mongo

  ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    image: g31-ui:latest
    env_file:
      - ./ui/.env
    # environment:
    #   - NODE_ENV=production
    #   - NEXT_PUBLIC_USER_SERVICE_BASE_URL=${NEXT_PUBLIC_USER_SERVICE_BASE_URL:-http://localhost:4001}
    ports:
      - "3000:3000"
    depends_on:
      - user-service

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/db

  mongo:
    image: mongo
    command: "mongod --replSet rs0 --bind_ip_all --port 27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./config/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  redis_data:
  mongo_data:


networks:
  default:
    name: g31-network
